version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src:/app/src       
      - shared_data:/app/out
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./data:/data
      - shared_data:/app/out
    working_dir: /app
volumes:
    pgdata:
    shared_data:
